### ISSUE TITLE
Bug report: unexpected behaviour when running 2 games at the same time on different tabs

### ISSUE THREAD

**Issue by uo283928** [Arquisoft/wiq_en2b#122]
When testing the application I tried to create 2 games at the same time. I have done this twice but two different responses were given. First, a 304 and then, a 403.

Output on screen was the same as in #121

**Comment by jjgancfer** [comment]
Both @gony02 and I cannot reproduce it. We have been touching how authentication works, so we probably have already unknowingly fixed it.

**Comment by jjgancfer** [comment]
@uo283928 has confirmed the bug seems to be solved, so I'm closing the issue.
