### ISSUE TITLE
Redirecting to home whenever an endpoint does not exist

### ISSUE THREAD

**Issue by uo283928** [Arquisoft/wiq_en2b#123]
I believe it would be great if whenever a wrong endpoint is accessed, it redirects to a home page instead of throwing a 404 error.
I am unsure where should we redirect to, I believe the best options are either login or home page. We have to be careful about sessions in both cases. 
What are your opinions on this?

**Comment by jjgancfer** [comment]
Marked as duplicated due to being superseded by #125.
