### ISSUE TITLE
Creating new branch for source modifications before first deliverable

### ISSUE THREAD

**Issue by jjgancfer** [Arquisoft/wiq_en2b#13]
Given that for the first deliverable we have to make a deployment of the code, I think we should create a branch and merge all initial modifications there, so as to keep the project directory as clean as possible.

**Comment by sergiorodriguezgarcia** [comment]
I completely agree with the idea. I think creating a branch and merging all the initial mods into it is a great way to keep the project directory tidy, especially since for the first deliverable we need to deploy the initial code. For me, let's go ahead and carry out that proposal.

**Comment by Toto-hitori** [comment]
I approve this decision :)

**Comment by jjgancfer** [comment]
I have already created the branch (`initial-modifications`), so please be sure to leave develop in this delivery for things related to documentation and deployment.
