### ISSUE TITLE
Add e2e tests

### ISSUE THREAD

**Issue by Toto-hitori** [Arquisoft/wiq_en2b#143]
End 2 End tests shall be added to our application:
https://medium.com/@francislainy.campos/integrating-cucumber-into-a-spring-boot-project-a-step-by-step-guide-f899c04bf81f

**Comment by uo283928** [comment]
Acceptance tests done already

**Comment by uo283928** [comment]
E2e test cases implemented and properly working without race conditions. Both positive and negative cases were included.
No PR as pushed to develop by mistake, my bad.
Test must be run locally as they are out of the deployment pipeline due to database needs.
