### ISSUE TITLE
Update the documentation

### ISSUE THREAD

**Issue by gony02** [Arquisoft/wiq_en2b#185]
# Changes to be applied:
- [x] Updating icon
- [x] Updating title
- [x] C4 model (already done by @Toto-hitori, just was not pushed to master)

## 2 Architectural constraints (to be done by @gony02)
- [x] Updating wireframes 

## 4 Solution strategy
- [x] Adding SpringBoot version

### 5.1
- [ ] Adding interfaces to overview diagram (to be done once HTTPS is fully implemented)
### 5.2
- [ ] Adding proxy for HTTPS (to be done once HTTPS is fully implemented)
- [x] Adding question generator module
- [x] Adding interfaces description

### 6.1 
- [x] Adding rounds workflow (already done by @Toto-hitori, just was not pushed to master)
- [x] Fix question calls (already done by @Toto-hitori, just was not pushed to master)
### 6.4 
- [x] Adding Dto as transfer mean (already done by @Toto-hitori, just was not pushed to master)

## 7 Deployment view
- [x] Missing question generator module in the diagram

## 8 Cross-cutting concepts (to be done by @UO283615)
- [x] Modifying diagrams
- [x] Modifying descriptions (if necessary)

## 9 Architectural decisions
- [x] Adding question generator module
- [x] Adding HTTPS
- [x] Link the architectural decisions to the wiki
- [x] Move current architectural decisions to the wiki section

###  10.2.1
- [x] Updating the % of availability
- [x] Updating the % of testability
- [ ] Adding descriptions for tests done (to be done once all the tests are defined)

## 12 Glossary
- [ ] Adding important concepts

**Comment by jjgancfer** [comment]
The updated documentation has already been deployed.
