### ISSUE TITLE
Self reports: Third delivery

### ISSUE THREAD

**Issue by gony02** [Arquisoft/wiq_en2b#194]
Please comment on this issue with your self reports. Remember to vote on each other's reports and to follow the template that we used in the previous ones.

**Comment by gony02** [comment]
For this delivery I worked on:
### Pull requests 🪢
- #138 
	- #131
- #150 
	- #133 
	- #139
- #151
	- #133 
	- #139
- #163
	- #158
- #165
	- #186
- #190 
	- #185

### Issues ✍️
- Roadmap: #124

#### Related with the documentation 📄
- I have updated the wireframes, logo, and title of the documentation: #185

#### Related with the webapp 🥝
- Internationalised the application: #6
- Implemented frontend error messages: #131
- Resolved bugs in the web application: 
	- #121 
	- #122
- Designed a project icon and added a favicon: #133
- Completely revamped the application's appearance and user experience: #139
- Integrated a side menu into the application: #158
- Introduced a timer on the Game page of the web application: #184
- I have done testing on the web application: #186

### Wiki 📖
Moreover, I have written several pages on the Wiki and I have actively engaged in various meetings.
- [Home](https://github.com/Arquisoft/wiq_en2b/wiki)
- [12/03/2024](https://github.com/Arquisoft/wiq_en2b/wiki/Minutes-for-the-12-03-2024-session)
- [19/03/2024](https://github.com/Arquisoft/wiq_en2b/wiki/Minutes-for-the-19-03-2024-session)
- [28/03/2024](https://github.com/Arquisoft/wiq_en2b/wiki/Minutes-for-the-28-03-2024-reunion)
- [02/04/2024](https://github.com/Arquisoft/wiq_en2b/wiki/Minutes-for-the-02-04-2024-laboratory-session)

### Other 👨‍💻
For this third delivery, I have redesigned all the wireframes of the application, which I have included in the [documentation](https://arquisoft.github.io/wiq_en2b/) (refer to Section 2: Integration Constraints). Then, I have changed the entire look and feel of the application using [React](https://react.dev/) with [Chakra UI](https://chakra-ui.com/). Moreover, I have created a side menu that you can access at any time within the application. I have created a new view called About. I have also created a new app logo and icon. Additionally, I collaborated on updating the communication of the Game view with the new backend endpoints. In addition, I have helped my teammates solve problems in the backend and create acceptance tests. Finally, I have done unit tests for various views of the web app, aiming for at least 80% coverage in SonarCloud.

**Comment by UO283615** [comment]
For this delivery I worked on:
### Pull requests with their related issues 🪢
#### Related with the backend🥝
- #152
- #159
- #161
- #182
#### Related with the documentation 📄
- #191
- #193
- #195

### Issues ✍️
- Roadmap: #124

#### Related with the documentation 📄
- #185

#### Related with the backend 🥝
- #119 

### Wiki 📖
Moreover, I have engaged in various meetings.
- [Home](https://github.com/Arquisoft/wiq_en2b/wiki)
- [12/03/2024](https://github.com/Arquisoft/wiq_en2b/wiki/Minutes-for-the-12-03-2024-session)
- [19/03/2024](https://github.com/Arquisoft/wiq_en2b/wiki/Minutes-for-the-19-03-2024-session)
- [28/03/2024](https://github.com/Arquisoft/wiq_en2b/wiki/Minutes-for-the-28-03-2024-reunion)
- [02/04/2024](https://github.com/Arquisoft/wiq_en2b/wiki/Minutes-for-the-02-04-2024-laboratory-session)

### Other 👨‍💻
I have added new category of questions as well as new types, the latter have not been added yet to our application as it would need several changes in the front. I have also simplified our model to make the application more maintainable. I have also participated in the redesign of the game and solved several bugs.

**Comment by Toto-hitori** [comment]
For this delivery I worked on:
### Pull requests with their related issues 🪢
#### Related with the webapp 🥝
- #199 
#### Related with the documentation 📄
- #128
- #144
#### Related with the backend 🥝
- #137 
- #142 
- #153
- #199 

### Issues ✍️
- Roadmap: #124
- #117 
- #125 


#### Related with the documentation 📄
- I have aided in the creation of Swagger documentation: #129
- #185
#### Related with the backend 🥝
- #125 
- #130 
- #132 
- #136 

### Other 👨‍💻
For this third delivery, I have aided in the deployment, as well as fixing errors found in the front end of the application.

**Comment by uo283928** [comment]
For this delivery I worked on:
### Pull requests with their related issues 🪢
#### Related with the webapp 🥝
- Acceptance tests
	- #181 

#### Related with the documentation 📄 
- Updating the documentation and leaving the HTTPS documentations to be done as soon as it is fully implemented
	- #192 

### Issues ✍️
- Getting a free second level domain
	- #118 
- Bugfixing
	- #121 
	- #122 


#### Related with the backend
- Taking care of the Swagger
	- #144 
	- #167  

### Wiki 📖
Moreover, I have written several pages on the Wiki and I have actively engaged in various meetings.
- [Home](https://github.com/Arquisoft/wiq_en2b/wiki)
- [12/03/2024](https://github.com/Arquisoft/wiq_en2b/wiki/Minutes-for-the-12-03-2024-session)
- [19/03/2024](https://github.com/Arquisoft/wiq_en2b/wiki/Minutes-for-the-19-03-2024-session)
- [28/03/2024](https://github.com/Arquisoft/wiq_en2b/wiki/Minutes-for-the-28-03-2024-reunion)
- [02/04/2024](https://github.com/Arquisoft/wiq_en2b/wiki/Minutes-for-the-02-04-2024-laboratory-session)

### Other 👨‍💻
For this third delivery, as we aimed for improving the overall health of the code so I took more of a supportive role. This is why I mainly focused on documentation and testing, as many of my teammates.

**Comment by sergiorodriguezgarcia** [comment]
For this delivery I worked on:
### Pull requests with their related issues 🪢
#### Related with the webapp 🥝
- #135
	- #134
- #182
- #183
- #202 

### Issues ✍️
- Roadmap: #124

#### Related with the webapp 🥝
- I have introduced a timer on the Game page of the web application:
- #184
- I have done unit testing on the web application:
- #186

### Wiki 📖
Moreover, I have actively engaged in various meetings.
- [Home](https://github.com/Arquisoft/wiq_en2b/wiki)
- [12/03/2024](https://github.com/Arquisoft/wiq_en2b/wiki/Minutes-for-the-12-03-2024-session)
- [19/03/2024](https://github.com/Arquisoft/wiq_en2b/wiki/Minutes-for-the-19-03-2024-session)
- [28/03/2024](https://github.com/Arquisoft/wiq_en2b/wiki/Minutes-for-the-28-03-2024-reunion)
- [02/04/2024](https://github.com/Arquisoft/wiq_en2b/wiki/Minutes-for-the-02-04-2024-laboratory-session)

### Other 👨‍💻
For this third delivery,I collaborated on updating the communication of the Game view with the new backend endpoints and adding a timer to the rounds. Finally, I have done unit tests for various views of the web app, aiming for at least 80% coverage in SonarCloud.

**Comment by jjgancfer** [comment]
For this delivery I worked on:
### Pull requests 🪢

- #127 
- #145 
- #147 
- #149 
- #148 
- #151 
- #156 
- #166 
- #168
- #171 
- #172 
- #174 
- #198 
- #200

### Issues ✍️

- Roadmap: #124
- #6 
- #143 
- #178
- #177 
- #157
- #145 
- #146
- #141 
- #140 
- #126 
- #125

### Wiki 📖

I have also written the wiki for the following day:

- [28/03/2024](https://github.com/Arquisoft/wiq_en2b/wiki/Minutes-for-the-28-03-2024-reunion)

I have also participated in the following reunions:

- [12/03/2024](https://github.com/Arquisoft/wiq_en2b/wiki/Minutes-for-the-12-03-2024-session)
- [19/03/2024](https://github.com/Arquisoft/wiq_en2b/wiki/Minutes-for-the-19-03-2024-session)
- [02/04/2024](https://github.com/Arquisoft/wiq_en2b/wiki/Minutes-for-the-02-04-2024-laboratory-session)

### Other 👨‍💻
For this delivery, I have worked mainly in the webapp with @gony02 and @sergiorodriguezgarcia. I have improved @sergiorodriguezgarcia's initial implementation of AuthManager and I developed the statistics frontend. I included several small quality-of-life fixes that did not make sense to create their own pull request, and I have started to implement HTTPS, although sadly it did not make it to this release. Finally, on the night before the delivery, I fixed our first timezone-related bug alongside @Toto-hitori and @uo283928!

**Comment by sergioqfeg1** [comment]
For this delivery I worked on:
### Pull requests with their related issues 🪢
#### Related with the backend 🥝
- #189
- #176 
- #175 
- #173 
- #169 
- #153 

### Issues ✍️
- Roadmap: #124
- 
#### Related with the backend 🥝
- #130 

### Other 👨‍💻
For this delivery my task was to implement both the endpoints and the logic for the game workflow and the statistics.
