### ISSUE TITLE
Redesign the game logic and UI

### ISSUE THREAD

**Issue by jjgancfer** [Arquisoft/wiq_en2b#219]
The game logic needs some redesign to improve testing and code readability.

**Comment by gony02** [comment]
- [ ] Show the total number of rounds in the game
- [ ] Show the counter with numbers
- [ ] Give feedback to the user when an answer is wrong

**Comment by jjgancfer** [comment]
I am having problems with creating the feedback we had discussed, so I'll try to make it as simple as possible.

**Comment by jjgancfer** [comment]
Closed, due to the new logic and UI already have been merged, and only testing remains (see #186).
