### ISSUE TITLE
7. Deployment View

### ISSUE THREAD

**Issue by gony02** [Arquisoft/wiq_en2b#25]
7. Deployment View
    7.1. Infrastructure Level 1
    7.2. Infrastructure Level 2

**Comment by jjgancfer** [comment]
This part is awaiting review in #35.

**Comment by Toto-hitori** [comment]
Done: [Added sections 3 and part of 7 to the documentation](https://github.com/Arquisoft/wiq_en2b/pull/33) and [docs/jjgancfer](https://github.com/Arquisoft/wiq_en2b/pull/35)
