### ISSUE TITLE
8. Cross-cutting Concepts

### ISSUE THREAD

**Issue by gony02** [Arquisoft/wiq_en2b#26]
- 8. Cross-cutting Concepts (Diego - Gonzalo S)
    - 8.1. *<Concept 1>*
    - 8.2. *<Concept 2>*
    - 8.3. *<Concept n>*

**Comment by UO283615** [comment]
Related issue, #31.

**Comment by UO283615** [comment]
Closed thanks to this:
- #42
- #43
