### ISSUE TITLE
Enable HTTP/2

### ISSUE THREAD

**Issue by jjgancfer** [Arquisoft/wiq_en2b#51]
We should enable HTTP / 2 in both the frontend and the backend servers for an increased performance. In the latter, it should as easy as changing an application property, but in the former is not as easy because it deploys in nginx, not in an embedded Tomcat server. Nevertheless, I think it is worth looking into.

**Comment by uo283928** [comment]
I think it would be a great idea to implement it although I am unsure if we will have the time to implement it. 
It could be interesting too if HTTPS is enable too as many browsers block pages not using it and as it needs HTTP/2, I believe it is a good starting point. Maybe we could discuss about it in this week's session so I will search for it a bit.

**Comment by jjgancfer** [comment]
I looked into doing it for nginx: the most complicated part is the deployment, though I'm confident I can get it done.

**Comment by Toto-hitori** [comment]
Sure! As long as you can get it working I dont see why we should not enable it :)

**Comment by sergioqfeg1** [comment]
I think it could be a good idea to implement. And if it helps performance even better.

**Comment by gony02** [comment]
If it increases performance and is not very complicated, I am in favor of implementing it.

**Comment by UO283615** [comment]
If it is doable I think it would be right to implement it as it would improve the performance significantly.

**Comment by jjgancfer** [comment]
HTTP/2 in the API is currently awaiting review in #55. @Toto-hitori and I intend to implement HTTP/2 in the webapp as well as HTTPS next week.

**Comment by jjgancfer** [comment]
Due to time constraints, HTTP/2 and HTTPS support have been pushed back to next release.

**Comment by jjgancfer** [comment]
Closing this issue, as it has been superseded by #178.
