### ISSUE TITLE
Add architectural decisions to wiki

### ISSUE THREAD

**Issue by Toto-hitori** [Arquisoft/wiq_en2b#63]
The architectural decisions shall be added with their corresponding justifications.

**Comment by jjgancfer** [comment]
I am intend to create an issue instead of adding them to the wik because the wiki sidebar is already cluttered with the minutes record. What do you think of it?

**Comment by Toto-hitori** [comment]
I am not sure I agree with this, I still believe the wiki should be the place to record this kind of decisions and not clutter the issues more.

**Comment by jjgancfer** [comment]
I have already including some of the architectural decisions we have made so far. I will be adding more whenever I can.

**Comment by uo283928** [comment]
Great, I will also take a look when I get some spare time.

**Comment by UO283615** [comment]
I added the question generator architectural decission to the wiki
