### ISSUE TITLE
Bug report: POST to API endpoint /auth/login returns 403 error in Postman and fails in the browser

### ISSUE THREAD

**Issue by jjgancfer** [Arquisoft/wiq_en2b#66]
## Bug description

When making a POST request to the `auth/login` endpoint through Postman following the schema of the `lab.en2b.quizapi.auth.dtos.LoginDto` class, I receive a 403 error.

## Expected behaviour

Receive a response containing an object following the schema of the `lab.en2b.quizapi.auth.dtos.JwtResponseDto` class.

## Steps to reproduce

1. Set up the API as explained in [here](https://towering-glove-26e.notion.site/Development-instructions-245ab902400542d79d3b347bac4409ad).
2. Using Postman, send the following data:
![imagen](https://github.com/Arquisoft/wiq_en2b/assets/77108019/2814fb2c-ae74-4159-8f3f-9f76194c2f36)

## Extra information
When reproducing using the GUI of the `/login` endpoint through Firefox 123, the following result came up. It seems the problem is with the CORS policy, as the URI is correct.

![imagen](https://github.com/Arquisoft/wiq_en2b/assets/77108019/543c59a5-21c3-4eb3-95b0-27d22eb74b57)

**Comment by Toto-hitori** [comment]
I imagine before sending the login request you have first registered into the appication? If so please make sure that the account has been previously been registered into the database.  If this is the case the error message that you get is **No value present** which means that an account has not been created with those credentials. (I will make the error more descriptive from now on)
Also, I do not want to hit you with an "It works in my machine but it does haha"
![imagen](https://github.com/Arquisoft/wiq_en2b/assets/91892789/74940c4b-ce36-420f-a844-c7d4b7eaa074)

**Comment by jjgancfer** [comment]
I did not. I was testing out what kind of schema should be expected in both error and non-error, and when a 403 error was returned I interpreted it as an error (specially with the part regarding CORS).

Marked as closed.
