### ISSUE TITLE
Add logout endpoint to Authentication Service

### ISSUE THREAD

**Issue by Toto-hitori** [Arquisoft/wiq_en2b#78]

**Comment by jjgancfer** [comment]
A logout endpoint to the webapp should also be added.

**Comment by Toto-hitori** [comment]
For the logout endpoint the following approach was chosen in #87 :
When called the **/logout** method will delete the refresh token from the database, no longer allowing for its refresh until **/login** is called again. The JWT token though, will not be invalidated and shall expire naturally. Due to the short lifespan nature of the JWT tokens (1hour or so) this does not represent a significant security flaw and simplifies implementation.

**Comment by jjgancfer** [comment]
The API logout endpoint has already been merged into develop.

**Comment by Toto-hitori** [comment]
The login and logout should be fixed since they dont redirect to the proper things in the frontend.

**Comment by gony02** [comment]
Right now, the logout is working.
